name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install Java and Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk wget apt-transport-https unzip
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

        # Adicionando e instalando o SDK Android
        mkdir -p $HOME/Android/Sdk
        export ANDROID_HOME=$HOME/Android/Sdk
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip
        unzip commandlinetools-linux-7302050_latest.zip -d $HOME/Android/Sdk/cmdline-tools
        rm commandlinetools-linux-7302050_latest.zip
        mkdir -p $HOME/Android/Sdk/cmdline-tools/latest
        mv $HOME/Android/Sdk/cmdline-tools/* $HOME/Android/Sdk/cmdline-tools/latest

        # Instalando platform-tools
        yes | $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME --install "platform-tools" "build-tools;30.0.3"

        # Atualizando o PATH
        echo "export ANDROID_HOME=$HOME/Android/Sdk" >> $GITHUB_ENV
        echo "export PATH=$PATH:$ANDROID_HOME/platform-tools" >> $GITHUB_ENV
        echo "export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_ENV

    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https unzip
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
        # Obtém a versão instalada do Chrome
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
        # Obtém a versão do ChromeDriver correspondente
        CHROME_DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")

        # Faz download do ChromeDriver
        wget -N https://storage.googleapis.com/chrome-for-testing-public/132.0.6834.159/linux64/chromedriver-linux64.zip
        
        if [ -f "chromedriver-linux64.zip" ]; then
            echo "Arquivo ChromeDriver encontrado, descompactando..."
            unzip -q chromedriver-linux64.zip
            sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
            sudo chmod +x /usr/local/bin/chromedriver
        else
            echo "Erro: ChromeDriver não foi baixado."
            exit 1
        fi
    - name: Stop Chrome if running
      run: |
          adb shell am force-stop com.android.chrome || true

    - name: Run API Tests
      run: mvn -f restAssuredTest/pom.xml test

    - name: Run E2E Tests
      run: mvn -f cucumber-selenium-test/pom.xml test

    - name: Run Mobile Tests 1
      run: mvn -f MyAppiumProject-SauceLabs/pom.xml test

    - name: Run Mobile Tests 2
      run: mvn -f MyAppiumProjet-OnlineForm/pom.xml test